### ISSUE TITLE
Keeping track of online users

### ISSUE THREAD

**Issue by SirwanAfifi** [VahidN/DNTIdentity#1]
Thanks for sharing the project. well-done 👍 👍 

In my application I want to keep track of online users. Based on the project what I have found so far:

- Adding appropriate field (`LastVisitDateTime`)
- Customizing `SecurityStampValidator<User>`
- Customizing `SignInManager<User>`
- Registering appropriate services:
```
services.AddScoped<ISecurityStampValidator, CustomSecurityStampValidator>();
services.AddScoped<SecurityStampValidator<User>, CustomSecurityStampValidator>();

services.AddScoped<IApplicationSignInManager, ApplicationSignInManager>();
services.AddScoped<SignInManager<User>, ApplicationSignInManager>();

```
I just followed this process, but after log-in, the browser redirects me to a blank page, Here's my identity setup:
```
services.AddIdentity<User, IdentityRole>()
                .AddEntityFrameworkStores<AppDbContext>()
                .AddDefaultTokenProviders();

services.AddScoped<ISecurityStampValidator, CustomSecurityStampValidator>();
services.AddScoped<SecurityStampValidator<User>, CustomSecurityStampValidator>();

services.AddScoped<IApplicationSignInManager, ApplicationSignInManager>();
services.AddScoped<SignInManager<User>, ApplicationSignInManager>();

services.Configure<IdentityOptions>(options =>
{
       //options.Password.RequiredLength = 8;
       //options.Lockout.DefaultLockoutTimeSpan = TimeSpan.FromMinutes(30);                   
       //options.User.RequireUniqueEmail = true;
          options.Cookies.ApplicationCookie.AccessDeniedPath = new PathString("/Account/Login");
});
```
Is there something else to to?

**Comment by VahidN** [comment]
- You can't use `AddEntityFrameworkStores` anymore when you are customizing everything, because it will override all of the customized services. [It's explained here](http://www.dotnettips.info/post/2578/%d8%b3%d9%81%d8%a7%d8%b1%d8%b4%db%8c-%d8%b3%d8%a7%d8%b2%db%8c-asp-net-core-identity-%d9%82%d8%b3%d9%85%d8%aa-%d8%af%d9%88%d9%85-%d8%b3%d8%b1%d9%88%db%8c%d8%b3%e2%80%8c%d9%87%d8%a7%db%8c-%d9%be%d8%a7%db%8c%d9%87).
- Also it uses [SiteStatService](https://github.com/VahidN/DNTIdentity/blob/master/src/ASPNETCoreIdentitySample.Services/Identity/SiteStatService.cs) and [OnlineUsersViewComponent](https://github.com/VahidN/DNTIdentity/tree/master/src/ASPNETCoreIdentitySample/Areas/Identity/ViewComponents).
